config/routes.rb
MailSuite::Application.routes.draw do
  resources :vacations

  resources :mailboxes

  resources :logs

  resources :domain_admins

  resources :domains

  resources :aliases

  resources :admins

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/domain_admin.rb
class DomainAdmin < ActiveRecord::Base
  self.table_name = 'domain_admins'
  self.primary_key = :username

  extend FriendlyId
  friendly_id :username, use: :slugged

  validates :username, presence: true
  validates :domain, presence: true
end

app/controllers/domain_admins_controller.rb
class DomainAdminsController < ApplicationController
  before_action :set_domain_admin, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /domain_admins
  # GET /domain_admins.json
  def index
    @domain_admins = DomainAdmin.all.page params[:page]
  end

  # GET /domain_admins/1
  # GET /domain_admins/1.json
  def show
  end

  # GET /domain_admins/new
  def new
    @domain_admin = DomainAdmin.new
  end

  # GET /domain_admins/1/edit
  def edit
  end

  # POST /domain_admins
  # POST /domain_admins.json
  def create
    @domain_admin = DomainAdmin.new(domain_admin_params)

    respond_to do |format|
      if @domain_admin.save
        format.html { redirect_to @domain_admin, notice: 'Domain admin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @domain_admin }
      else
        format.html { render action: 'new' }
        format.json { render json: @domain_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domain_admins/1
  # PATCH/PUT /domain_admins/1.json
  def update
    respond_to do |format|
      if @domain_admin.update(domain_admin_params)
        format.html { redirect_to @domain_admin, notice: 'Domain admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @domain_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domain_admins/1
  # DELETE /domain_admins/1.json
  def destroy
    @domain_admin.destroy
    respond_to do |format|
      format.html { redirect_to domain_admins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain_admin
      @domain_admin = DomainAdmin.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_admin_params
      params.require(:domain_admin).permit(:username, :domain, :created, :active)
    end
end

app/helpers/domain_admins_helper.rb
module DomainAdminsHelper
end

app/views/domain_admins/_form.html.haml
= simple_form_for(@domain_admin) do |f|
  = f.error_notification
  - created = action_name == 'edit' || action_name == 'update' ? @domain_admin.created : Time.now.utc
  .form-inputs
    = f.input :username do
      = f.select :username, Admin.all.map { |d| [d.username] }, include_blank: true
    = f.input :domain do
      = f.select :domain, Domain.all.map { |d| [d.domain] }, include_blank: true
    = f.input :created, as: :hidden, input_html: { value: created }
    = f.input :active

  .form-actions
    = f.button :submit

  = hidden_field_tag 'action', nil, data: { action: action_name }

app/views/domain_admins/edit.html.haml
%h1 Editing domain_admin

= render 'form'

= link_to 'Show', @domain_admin
\|
= link_to 'Back', domain_admins_path

app/views/domain_admins/index.html.haml
%h1 Domain Admins
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Domain
        %th Active
        %th
        %th
        %th= link_to 'New Domain admin', new_domain_admin_path
    %tbody
      - @domain_admins.each do |domain_admin|
        %tr
          %td= mail_to domain_admin.username
          %td= domain_admin.domain
          %td= domain_admin.active
          %td= link_to 'Show', domain_admin
          %td= link_to 'Edit', edit_domain_admin_path(domain_admin)
          %td= link_to 'Destroy', domain_admin, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = paginate @domain_admins
  = page_entries_info @domain_admins

app/views/domain_admins/new.html.haml
%h1 New domain_admin

= render 'form'

= link_to 'Back', domain_admins_path

app/views/domain_admins/show.html.haml
%h1 Domain Admin
%p
  %b Username:
  = mail_to @domain_admin.username
%p
  %b Domain:
  = @domain_admin.domain
%p
  %b Created:
  = @domain_admin.created
%p
  %b Active:
  = @domain_admin.active

= link_to 'Edit', edit_domain_admin_path(@domain_admin)
\|
= link_to 'Back', domain_admins_path