config/routes.rb
MailSuite::Application.routes.draw do
  resources :vacations

  resources :mailboxes

  resources :logs

  resources :domain_admins

  resources :domains

  resources :aliases

  resources :admins

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  self.table_name = 'vacation'

  extend FriendlyId
  friendly_id :email, use: :slugged

  validates :email, presence: true

  before_save :clean_domain

  private
  def clean_domain
    self.domain = self.domain.gsub('@', '')
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all.page params[:page]
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vacation }
      else
        format.html { render action: 'new' }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      params.require(:vacation).permit(:email, :subject, :body, :cache, :domain, :created, :active)
    end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.haml
= simple_form_for(@vacation) do |f|
  = f.error_notification
  - created = action_name == 'edit' || action_name == 'update' ? @vacation.created : Time.now.utc
  .form-inputs
    = f.input :email do
      = f.select :email, Mailbox.all.map { |d| [d.username] }, include_blank: true
    = f.input :subject
    = f.input :body
    = f.input :cache
    = f.input :domain
    = f.input :created, as: :hidden, input_html: { value: created }
    = f.input :active

  .form-actions
    = f.button :submit

  = hidden_field_tag 'action', nil, data: { action: action_name }

app/views/vacations/edit.html.haml
%h1 Editing vacation

= render 'form'

= link_to 'Show', @vacation
\|
= link_to 'Back', vacations_path

app/views/vacations/index.html.haml
%h1 Vacations
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Email
        %th Subject
        %th Domain
        %th Active
        %th
        %th
        %th= link_to 'New Vacation', new_vacation_path
    %tbody
      - @vacations.each do |vacation|
        %tr
          %td= vacation.email
          %td= vacation.subject
          %td= vacation.domain
          %td= vacation.active
          %td= link_to 'Show', vacation
          %td= link_to 'Edit', edit_vacation_path(vacation)
          %td= link_to 'Destroy', vacation, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = paginate @vacations
  = page_entries_info @vacations

app/views/vacations/new.html.haml
%h1 New vacation

= render 'form'

= link_to 'Back', vacations_path

app/views/vacations/show.html.haml
%h1 Vacation
%p
  %b Email:
  = @vacation.email
%p
  %b Subject:
  = @vacation.subject
%p
  %b Body:
  = @vacation.body
%p
  %b Cache:
  = @vacation.cache
%p
  %b Domain:
  = @vacation.domain
%p
  %b Created:
  = @vacation.created
%p
  %b Active:
  = @vacation.active

= link_to 'Edit', edit_vacation_path(@vacation)
\|
= link_to 'Back', vacations_path