config/routes.rb
MailSuite::Application.routes.draw do
  resources :vacations

  resources :mailboxes

  resources :logs

  resources :domain_admins

  resources :domains

  resources :aliases

  resources :admins

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    alias_action :index, :show, :to => :read
    alias_action :new, :create, :to => :write
    alias_action :edit, :update, :to => :modify
    alias_action :destroy, :confirm_destroy, :to => :delete

    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :user
        can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  self.table_name = 'admin'

  extend FriendlyId
  friendly_id :username, use: :slugged

  validates :username, presence: true
  validates :password, presence: true

  before_save :crypt_password

  private
  def crypt_password
    self.password = Digest::MD5.hexdigest(self.password)
  end
end

app/models/alias.rb
class Alias < ActiveRecord::Base
  self.table_name = 'alias'

  extend FriendlyId
  friendly_id :address, use: :slugged

  validates :address, presence: true
  validates :goto, presence: true
  validates :domain, presence: true
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  self.table_name = 'domain'

  extend FriendlyId
  friendly_id :domain, use: :slugged

  validates :domain, presence: true
end

app/models/domain_admin.rb
class DomainAdmin < ActiveRecord::Base
  self.table_name = 'domain_admins'
  self.primary_key = :username

  extend FriendlyId
  friendly_id :username, use: :slugged

  validates :username, presence: true
  validates :domain, presence: true
end

app/models/log.rb
class Log < ActiveRecord::Base
  self.table_name = 'log'

  extend FriendlyId
  friendly_id :timestamp, use: :slugged
end

app/models/mailbox.rb
class Mailbox < ActiveRecord::Base
  self.table_name = 'mailbox'

  extend FriendlyId
  friendly_id :username, use: :slugged

  validates :username, presence: true
  validates :password, presence: true
  validates :domain, presence: true

  before_save :crypt_password
  before_create :merge_username

  private
  def crypt_password
    self.password = Digest::MD5.hexdigest(self.password)
  end

  def merge_username
    self.username = self.username << '@' << self.domain
    self.slug = self.username.gsub('@', '-').gsub('.', '-')
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_role

  private
  def create_role
    add_role :user
  end
end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  self.table_name = 'vacation'

  extend FriendlyId
  friendly_id :email, use: :slugged

  validates :email, presence: true

  before_save :clean_domain

  private
  def clean_domain
    self.domain = self.domain.gsub('@', '')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_authorization_check

  def index
    @users = User.all.page params[:page]
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :destroy]

  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all.page params[:page]
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.friendly.find(params[:id])
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/admins/_form.html.haml
= simple_form_for(@admin) do |f|
  = f.error_notification
  - disabled = action_name == 'edit' || action_name == 'update' ? true : false
  - created = action_name == 'edit' || action_name == 'update' ? @admin.created : Time.now.utc
  .form-inputs
    = f.input :username, :disabled => disabled
    = f.input :password
    = f.input :created, as: :hidden, input_html: { value: created }
    = f.input :modified, as: :hidden, input_html: { value: Time.now.utc }
    = f.input :active

  .form-actions
    = f.button :submit

app/views/admins/edit.html.haml
%h1 Editing admin

= render 'form'

= link_to 'Show', @admin
\|
= link_to 'Back', admins_path

app/views/admins/index.html.haml
%h1 Admins
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Active
        %th
        %th
        %th= link_to 'New Admin', new_admin_path
    %tbody
      - @admins.each do |admin|
        %tr
          %td= mail_to admin.username
          %td= admin.active
          %td= link_to 'Show', admin
          %td= link_to 'Edit', edit_admin_path(admin)
          %td= link_to 'Destroy', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = paginate @admins
  = page_entries_info @admins

app/views/admins/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/admins/show.html.haml
%h1 Admin
%p
  %b Username:
  = mail_to @admin.username
%p
  %b Created:
  = @admin.created
%p
  %b Modified:
  = @admin.modified
%p
  %b Active:
  = @admin.active

= link_to 'Edit', edit_admin_path(@admin)
\|
= link_to 'Back', admins_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Accounts', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

- if user_signed_in?
  %p= render 'layouts/tabs'

app/views/layouts/_tabs.html.haml
%ul.nav
  %li= link_to 'Admins', admins_path
  %li= link_to 'Domain Admins', domain_admins_path
  %li= link_to 'Domains', domains_path
  %li= link_to 'Aliases', aliases_path
  %li= link_to 'Mailboxes', mailboxes_path
  %li= link_to 'Vacations', vacations_path
  %li= link_to 'Logs', logs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Mail Suite"
      %meta{:content => content_for?(:description) ? yield(:description) : "Mail Suite", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button{type: "button", class: "navbar-toggle collapsed", "data-toggle": "collapse", "data-target": "#bs-navbar-collapse", "aria-expanded": "false"}
            %span.sr-only = "Toggle navigation"
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Mail Suite", root_path, :class => 'navbar-brand'
        .collapse.navbar-collapse{:id => "bs-navbar-collapse"}
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main