config/routes.rb
MailSuite::Application.routes.draw do
  resources :vacations

  resources :mailboxes

  resources :logs

  resources :domain_admins

  resources :domains

  resources :aliases

  resources :admins

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  self.table_name = 'domain'

  extend FriendlyId
  friendly_id :domain, use: :slugged

  validates :domain, presence: true
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all.page params[:page]
    modified = @domains.maximum(:modified)
    fresh_when etag: @domains, last_modified: modified, public: true
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    fresh_when etag: @domain, last_modified: @domain.modified, public: true
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
    @aliases = Alias.where(domain: @domain.domain)
    @mailboxes = Mailbox.where(domain: @domain.domain)
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render action: 'show', status: :created, location: @domain }
      else
        format.html { render action: 'new' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:domain, :description, :aliases, :mailboxes, :maxquota, :transport, :backupmx, :created, :modified, :active)
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.haml
= simple_form_for(@domain) do |f|
  = f.error_notification
  - disabled = action_name == 'edit' || action_name == 'update' ? true : false
  - maxquota = action_name == 'edit' || action_name == 'update' ? @domain.maxquota : '10'
  - created = action_name == 'edit' || action_name == 'update' ? @domain.created : Time.now.utc
  .form-inputs
    = f.input :domain, :disabled => disabled
    = f.input :description
    - if action_name != 'new'
      = label_tag 'aliases'
      = select_tag 'aliases', options_for_select(@aliases.collect(&:address)), multiple: true, disabled: true
      = f.input :aliases, as: :hidden, input_html: { value: @aliases.count }
      = label_tag 'mailboxes'
      = select_tag 'mailboxes', options_for_select(@mailboxes.collect(&:username)), multiple: true, disabled: true
      = f.input :mailboxes, as: :hidden, input_html: { value: @mailboxes.count }
    = f.input :maxquota, input_html: { value: maxquota }
    = f.input :transport
    = f.input :backupmx
    = f.input :created, as: :hidden, input_html: { value: created }
    = f.input :modified, as: :hidden, input_html: { value: Time.now.utc }
    = f.input :active

  .form-actions
    = f.button :submit

app/views/domains/edit.html.haml
%h1 Editing domain

= render 'form'

= link_to 'Show', @domain
\|
= link_to 'Back', domains_path

app/views/domains/index.html.haml
%h1 Domains
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Domain
        %th Description
        %th Aliases
        %th Mailboxes
        %th Maxquota
        %th Transport
        %th Backupmx
        %th Active
        %th
        %th
        %th= link_to 'New Domain', new_domain_path
    %tbody
      - @domains.each do |domain|
        %tr
          %td= domain.domain
          %td= domain.description
          %td= domain.aliases
          %td= domain.mailboxes
          %td= domain.maxquota
          %td= domain.transport
          %td= domain.backupmx
          %td= domain.active
          %td= link_to 'Show', domain
          %td= link_to 'Edit', edit_domain_path(domain)
          %td= link_to 'Destroy', domain, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = paginate @domains
  = page_entries_info @domains

app/views/domains/new.html.haml
%h1 New domain

= render 'form'

= link_to 'Back', domains_path

app/views/domains/show.html.haml
%h1 Domain
%p
  %b Domain:
  = @domain.domain
%p
  %b Description:
  = @domain.description
%p
  %b Aliases:
  = @domain.aliases
%p
  %b Mailboxes:
  = @domain.mailboxes
%p
  %b Maxquota:
  = @domain.maxquota
%p
  %b Transport:
  = @domain.transport
%p
  %b Backupmx:
  = @domain.backupmx
%p
  %b Created:
  = @domain.created
%p
  %b Modified:
  = @domain.modified
%p
  %b Active:
  = @domain.active

= link_to 'Edit', edit_domain_path(@domain)
\|
= link_to 'Back', domains_path